### ISSUE TITLE
`mobc_pool_connections_idle` reports "connection limit" on start, and "connections left to connection limit" later

### ISSUE THREAD

**Issue by janpio** [importcjj/mobc#82]
`mobc_pool_connections_idle` is defined as `Number of currently unused Pool Connections (waiting for the next pool query to run)`.

But it is instantiated with `max_open`:
```
gauge!(IDLE_CONNECTIONS, max_open as f64);
```
https://github.com/importcjj/mobc/blob/f8c9779141ab3b8079d5dff0317273a7ee029998/src/lib.rs#L383C34-L383C43
`max_open` is defined as `Sets the maximum number of connections managed by the pool.`

That means that on start, it just reports the "connection limit", and then later the number of "connections left to connection limit".
Even though this might be an interesting metric, it is not what the description of the actual metric implies.

Instead of being initialized with `max_open`, this gauge should probably start at 0 and then reflect the difference between `mobc_pool_connections_open` and `mobc_pool_connections_busy`.

**Comment by garrensmith** [comment]
@janpio I see what you mean. But I'm not 100% convinced that `open - busy` for the idle connections would be any better. I think it might make it a but more confusing. 

Say a user sets the connection limit to 10. Then with the current idle metric setup:
When the app starts, it will have a "theoretical" limit of 10 idle connections. Theoretical because mobc doesn't create 10 connections at start but that is a design detail and not something we want the user of mobc to worry about. If 10 requests came in straight away we would create 10 connections. So the system is not saturated. Then an app takes one connection to service a query. Internally mobc will create the connection and return it. Mobc will then report it has 9 idle connections. It could service 9 connections at this point before being saturated. 

If we based idle connections on open and busy:
On start mobc would report 0 idle connections
Then an app requests a connection. Open = 1 and busy = 1, so idle would report 0. This would imply that the connection pool is saturated when it just hasn't needed to create any more connections. 

Does that make sense? Otherwise maybe we need a better name to describe that metric. Instead of `idle` maybe its number of available connections or waiting connections.

**Comment by janpio** [comment]
Yes, that is exactly the gist of the problem. 

"Idle" to me means "connection is open, but not doing anything right now". One source to confirm my understanding: https://aws.amazon.com/blogs/database/resources-consumed-by-idle-postgresql-connections/#:~:text=Linux%20manual.-,Idle%20connections,-Idle%20connections%20are
> A common explanation is that they’re just idle connections and not actually doing anything.

To express "mobc could potentially still create this many connections without hitting the max_open", then the name of the metrics should be completely different to express that.

**Comment by garrensmith** [comment]
I've been thinking about this a bit more. I think the name is fine. Its not 100% and the only alternative I could think of was `mobc_pool_connections_not_active`. 

The idle is still correct though. If we have 10 connections in the pool. And 10 requests for connections happen and then complete. Those 10 connections will be returned to the connection pool and will be idle. Mobc will always look to use an idle connection before trying to create one.

**Comment by janpio** [comment]
I think that would be changing the functionality of the metrics to be in line with its name.
When all 10 connections were used, and then one of those connections is closed, the idle will go down to 9.
The old metrics "connections that could be opened but are not yet" is more or less the opposite, and would then go from 0 to 1 again.

**Comment by garrensmith** [comment]
@janpio sounds good. I can try and get to this in the new week or so but if a Prisma engineer is interested they are welcome to fix it.

**Comment by garrensmith** [comment]
@janpio https://github.com/importcjj/mobc/pull/86 should fix this.
